#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

cd /

if [ ! -z ${INTPORT} ]; then
	port=$INTPORT
else
	port=6595
fi

DEEMIX_DATA_DIR=/config/
DEEMIX_MUSIC_DIR=/downloads/
DEEMIX_SERVER_PORT=$port
DEEMIX_HOST=0.0.0.0

echo "[services.d] Starting Deemix"
s6-setuidgid abc ./server