#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

cd /

if [ ! -z ${INTPORT} ]; then
	port=$INTPORT
else
	port=6595
fi


echo "export DEEMIX_DATA_DIR=/config/" >> /etc/environment
echo "export DEEMIX_MUSIC_DIR=/downloads/" >> /etc/environment
echo "export DEEMIX_SERVER_PORT=$port" >> /etc/environment
echo "export DEEMIX_HOST=0.0.0.0" >> /etc/environment
source /etc/environment

echo "[services.d] Starting Deemix"
s6-setuidgid abc ./server