#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

cd /

if [ ! -z ${INTPORT} ]; then
	port=$INTPORT
else
	port=6595
fi

echo "[services.d] Starting Deemix"
s6-setuidgid abc ./server